server:
  port: 9999
spring:
  application:
    name: gateway-server
  config:
    import:
      - optional:nacos:gateway-server.yml
      - optional:nacos:redis-config.yml?group=common&refreshEnable=true
      - optional:nacos:permission-config.yml?group=common&refreshEnable=true
      - optional:nacos:satoken-config.yml?group=common&refreshEnable=true
  cloud:
    nacos:
      server-addr: 192.168.50.240:8848
      discovery:
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a
        group: demo2024
      # 2022.0新配置
      config:
        group: demo2024
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a # 如果没有指定命令空间，则默认命令空间为PUBLIC
        file-extension: yaml
        encode: UTF-8
        timeout: 5000 # 从nacos读取配置项的超时时间
        max-retry: 3 # 长轮训重试次数
        config-long-poll-timeout: 1000 # 长轮训超时时间
        config-retry-time: 100000 # 重试时间
        enable-remote-sync-config: true # nacos的扩展配置项，数字越大优先级越高,# 监听器首次添加时拉取远端配置,false
        refresh-enabled: true # 开启监听和自动刷新
        # prefix: 文件名前缀，默认是spring.application.name
        extension-configs:
          # 可以添加其他节点
          - dataId: redis-config.yml
            group: common
            refresh: true
          - data-id: permission-config.yml
            group: common
            refresh: true
          - data-id: satoken-config.yml
            group: common
            refresh: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-server-route
          uri: lb://student-server # 路由的目标地址，lb表示负载均衡
          predicates: # 路由断言，判断请求是否符合路由规则
            - Path=/stu/** # 要求请求路径以/user/开头，否则404
          filters:
            - StripPrefix=1
        - id: shopping-server-route
          uri: lb://shopping-server
          predicates:
            - Path=/shop/**
          filters:
            - StripPrefix=1
        - id: auth-server-route
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      httpclient:
        pool:
          type: ELASTIC
          max-idle-time: 30S
          max-connections: 2000
        websocket:
          max-frame-payload-length: 10485760
    loadbalancer:
      enabled: true
      cache:
        enabled: true # 是否开启缓存
        ttl: 2s # 缓存失效时间
      nacos:
        enabled: true # 使用nacos权重需要开启
#      configurations: com.alibaba.cloud.nacos.loadbalancer.NacosLoadBalancerClientConfiguration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    # 重点在这里,默认为false,所以没有gateway相关端点,打开后就可以访问
    gateway:
      enabled: true
    refresh:
      enabled: true

logging:
  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework.HTTP.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug
    com.bob.*: info
  config: classpath:logback.xml