server:
  port: 8888
spring:
  application:
    name: auth-server
  config:
    import:
      - optional:nacos:auth-server.yml
      - optional:nacos:redis-config.yml?group=common&refreshEnable=true
      - optional:nacos:satoken-config.yml?group=common&refreshEnable=true
  cloud:
    nacos:
      server-addr: 192.168.50.240:8848
      discovery:
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a
        group: demo2024
      # 2022.0新配置
      config:
        group: demo2024
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a # 如果没有指定命令空间，则默认命令空间为PUBLIC
        file-extension: yaml
        encode: UTF-8
        timeout: 5000 # 从nacos读取配置项的超时时间
        max-retry: 3 # 长轮训重试次数
        config-long-poll-timeout: 1000 # 长轮训超时时间
        config-retry-time: 100000 # 重试时间
        enable-remote-sync-config: true # nacos的扩展配置项，数字越大优先级越高,# 监听器首次添加时拉取远端配置,false
        refresh-enabled: true # 开启监听和自动刷新
        # prefix: 文件名前缀，默认是spring.application.name
        extension-configs:
          # 可以添加其他节点
          - dataId: redis-config.yaml
            group: common
            refresh: true
          - dataId: satoken-config.yaml
            group: common
            refresh: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:/mapper/*/*/*.xml
  #  实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bob.student.*.domain
  global-config:
    db-config:
      logic-delete-field: del_flag # 逻辑删除字段
      logic-delete-value: 1 # 逻辑删除值
      logic-not-delete-value: 0 # 逻辑未删除值
logging:
  config: classpath:logback.xml
  level:
    com.bob.*: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'