server:
  port: 11000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    cache-enabled: true
    aggressive-lazy-loading: false
  mapper-locations: classpath:/mapper/*/*/*.xml
  #  实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tc.platformpeople.*.domain

logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    root: info

spring:
  application:
    name: demo2024-shopping-server
  profiles:
    active: dev
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.50.240:3306/demo2024_biz_shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: javaee12
      initial-size: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000


  cloud:
    nacos:
      server-addr: 192.168.50.240:8848
      discovery:
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a
        group: demo2024
      config:
        server-addr: 192.168.50.240:8848
        file-extension: yaml
        namespace: demo2024-ff70-43c5-89b6-06110ac8856a





