# nacos redis-config配置备份
spring:
  data:
    redis:
      host: 192.168.50.81
      port: 6379
      password: 123456
      database: 0
      timeout: 10000
      ssl: false
      client-type: jedis
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-wait: 10000
          max-idle: 10
          min-idle: 0