sa-token:
  token-name: BobToken # token 名称（同时也是 cookie 名称）
  dynamic-active-timeout: false # 开启active timeout
  timeout: 2592000 # token 有效期（单位：秒） 默认30天(2592000)，-1 代表永久有效
  active-timeout: -1 # 86400(24h) token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  is-concurrent: false # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-share: false # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  token-style: tik # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  is-log: true # 是否输出操作日志
  is-write-header: true
  is-read-header: true
  is-read-body: false
  is-read-cookie: false
  auto-renew: false
  max-try-times: 3